### ISSUE TITLE
result about imagenet 

### ISSUE THREAD

**Issue by jinwoojeon111** [Gank0078/BOAT#1]
First of all, thank you for the great research work. I have a question regarding the ImageNet results. For other datasets, the average and standard deviation were reported after running the experiments three times, but for ImageNet, only the result values are displayed. In this case, I’m wondering if the reported result is the average of three runs or if it is the best result among multiple experiments. I would appreciate your clarification on this. Thank you.

**Comment by Gank0078** [comment]
Thank you for your interests! The results for imagenet are only one run following CReST, CoSSL, and ACR due to excessive training duration.

**Comment by jinwoojeon111** [comment]
Thank you for kind reply!
